[build]
bin = "./tmp/ce"
cmd = "go build -o ./tmp/ce ./cmd/ce/main.go"
include_ext = ["go", "html", "js", "sql", "md", "json"]
include_dir = ["pkg", "cmd", "configs", "."]
exclude_dir = ["frontend", "tmp", ".git", "node_modules"]
send_interrupt = true
kill_delay = "500ms"

[run]
cmd = "APP_ENV=development ./tmp/ce"

[misc]
clean_on_exit = true
