package protocol

// SourceMaterial represents a specific code snippet or file used in the research.
type SourceMaterial struct {
	ID        string `json:"id"`         // Unique identifier for the source (e.g., "src-1")
	Path      string `json:"path"`       // Relative path to the file in the codebase
	Snippet   string `json:"snippet"`    // Relevant code snippet from the file
	StartLine int    `json:"start_line"` // Starting line number of the snippet
	EndLine   int    `json:"end_line"`   // Ending line number of the snippet
}

// ResearchTurn represents a single exchange in a research session.
type ResearchTurn struct {
	ID        string           `json:"id"`        // Unique identifier for this turn
	Query     string           `json:"query"`     // The user's original research question
	Report    string           `json:"report"`    // Markdown-formatted research analysis
	Sources   []SourceMaterial `json:"sources"`   // List of source materials referenced in the report
	Timestamp int64            `json:"timestamp"` // Unix timestamp of the research turn
}

// StepStatus represents the current state of a research step.
type StepStatus string

const (
	StepPending   StepStatus = "pending"
	StepActive    StepStatus = "active"
	StepCompleted StepStatus = "completed"
)

// StepUpdate represents a change in the status of a predefined research step.
type StepUpdate struct {
	ID     string     `json:"id"`     // ID of the step to update
	Status StepStatus `json:"status"` // New status for the step
}

// ResearchResponse is the final payload generated by the LLM.
type ResearchResponse struct {
	Report  string           `json:"report"`  // Markdown-formatted research analysis
	Sources []SourceMaterial `json:"sources"` // List of source materials referenced
}

// OpenAIStreamChunk represents a standard OpenAI-compatible text delta chunk.
type OpenAIStreamChunk struct {
	ID      string `json:"id"`
	Object  string `json:"object"`
	Created int64  `json:"created"`
	Model   string `json:"model"`
	Choices []struct {
		Index int `json:"index"`
		Delta struct {
			Content string `json:"content,omitempty"`
			Role    string `json:"role,omitempty"`
		} `json:"delta"`
		FinishReason *string `json:"finish_reason"`
	} `json:"choices"`
}

// CEEvent represents a custom Code Explorer research or tool event.
type CEEvent struct {
	Object   string          `json:"object"`
	ID       string          `json:"id,omitempty"`       // For step updates
	Status   StepStatus      `json:"status,omitempty"`   // For step updates
	Content  string          `json:"content,omitempty"`  // For reasoning deltas
	Tool     string          `json:"tool,omitempty"`     // For tool calls
	Params   any             `json:"params,omitempty"`   // For tool requests
	Response any             `json:"response,omitempty"` // For tool responses
	Source   *SourceMaterial `json:"source,omitempty"`   // For added sources
	Resource *SourceMaterial `json:"resource,omitempty"` // For resource materials
}
